create table loan
(
    loan_id            bigint generated by default as identity
        primary key,
    created_at         timestamp(6),
    created_by         varchar(255),
    updated_at         timestamp(6),
    updated_by         varchar(255),
    amount_paid        integer,
    loan_number        varchar(255),
    loan_type          varchar(255),
    mobile_number      varchar(255),
    outstanding_amount integer not null,
    total_loan         integer
);


INSERT INTO loan (
    created_at, created_by, updated_at, updated_by,
    amount_paid, loan_number, loan_type, mobile_number,
    outstanding_amount, total_loan
) VALUES
      ('2024-12-01 10:00:00', 'admin', '2024-12-15 12:00:00', 'admin',
       5000, 'LN001', 'Personal', '1234567890', 15000, 20000),
      ('2024-12-02 11:00:00', 'admin', '2024-12-16 13:00:00', 'admin',
       10000, 'LN002', 'Car', '9876543210', 20000, 30000),
      ('2024-12-03 14:00:00', 'user1', '2024-12-17 15:00:00', 'user2',
       15000, 'LN003', 'Home', '1122334455', 35000, 50000),
      ('2024-12-04 16:00:00', 'user2', '2024-12-18 17:00:00', 'user3',
       20000, 'LN004', 'Education', '9988776655', 10000, 30000),
      ('2024-12-05 18:00:00', 'admin', '2024-12-19 19:00:00', 'admin',
       25000, 'LN005', 'Business', '5544332211', 25000, 50000);
